apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\toder\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: studymaterial-service
  name: studymaterial-service
spec:
  ports:
    - name: "7071"
      port: 7071
      targetPort: 7071
  selector:
    io.kompose.service: studymaterial-service
status:
  loadBalancer: {}
